repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3.8
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '${HOME}/.venv/blu/bin/pip freeze > requirements-dev.txt; git add requirements-dev.txt'
        language: system
        pass_filenames: false
        stages: [commit]
